import { Router } from 'express';
import crypto from 'crypto';
import * as WidgetData from '../services/WidgetDataService.js';
import { validateWidget } from '../middleware/validate.js';
import * as SubService from '../services/SubmissionService.js';

const router = Router();

// ── Approval: DB-level atomic status check replaces in-memory lock ──
// On Vercel (serverless), each invocation is a separate instance,
// so in-memory locks are useless. Instead we use atomic DB updates:
// UPDATE ... WHERE request_status = 'PENDING' and check affected rows.

// ── GET /requests ──
router.get('/', async (req, res, next) => {
  try {
    const { status, date } = req.query;
    const requests = await SubService.fetchRequests(req.env, { status, date });
    res.json(requests);
  } catch (err) {
    console.error('[requests GET /] Database read failed:', err.message);
    res.status(502).json({ error: 'Failed to fetch requests from database', details: err.message });
  }
});

// ── POST /requests ──
router.post('/', async (req, res, next) => {
  try {
    const { widgetIds, widgets: inlineWidgets, headerWidgets } = req.body;

    // ── Path A: Inline widgets from frontend ──
    if (Array.isArray(inlineWidgets)) {
      const allErrors = [];
      for (let i = 0; i < inlineWidgets.length; i++) {
        const errors = validateWidget(inlineWidgets[i]);
        if (errors.length > 0) {
          allErrors.push({ index: i, widget: inlineWidgets[i].title || `Widget ${i}`, errors });
        }
      }
      if (allErrors.length > 0) {
        return res.status(400).json({ error: 'Validation failed', details: allErrors });
      }

      if (inlineWidgets.length === 0 && (!headerWidgets || Object.keys(headerWidgets).length === 0)) {
        return res.status(400).json({ error: 'At least 1 widget or header widget is required' });
      }

      // request_id generated by SubmissionService (numeric sequence)
      const requestId = null;

      // ── Step 1: Create widget records ──
      const createdWidgets = [];
      const STANDARD_KEYS = new Set([
        'type', 'slug', 'slug_name', 'title', 'titleHi',
        'pnc', 'config', 'products', 'sortOrder',
        'id', 'lastModified', 'lastModifiedBy', 'status',
        '_fetched', '_fromDB', '_dbId', '_rawData',
      ]);

      try {
        for (let i = 0; i < inlineWidgets.length; i++) {
          const w = inlineWidgets[i];
          const slug = w.slug || w.slug_name || `widget-${Date.now()}-${i}`;

          const extraConfig = {};
          for (const [k, v] of Object.entries(w)) {
            if (STANDARD_KEYS.has(k)) continue;
            if (typeof v === 'function') continue;
            extraConfig[k] = v;
          }

          const widget = await WidgetData.createWidget({
            type: w.type || 'unknown',
            slug, env: req.env,
            title: w.title || '', titleHi: w.titleHi || '',
            status: 'PENDING', sortOrder: i,
            pnc: w.pnc || {},
            config: { ...(w.config || {}), ...extraConfig },
            products: w.products || [],
            createdBy: req.user.email,
          });
          createdWidgets.push({ widget, original: w });
        }
      } catch (widgetErr) {
        // Rollback: soft-delete any widgets created before the failure
        for (const cw of createdWidgets) {
          try { await WidgetData.deleteWidget(cw.widget.widgetId, req.env); } catch { /* best-effort */ }
        }
        throw widgetErr;
      }

      // ── Step 2: Build submission with guaranteed server UUIDs + config ──
      const widgetsWithIds = inlineWidgets.map((w, i) => {
        const widgetId = createdWidgets[i]?.widget.widgetId;
        if (!widgetId) throw new Error(`Missing widget_id for widget index ${i}`);
        // Build config from non-standard fields (stateProducts, scrollItems, carouselItems, etc.)
        const widgetConfig = {};
        for (const [k, v] of Object.entries(w)) {
          if (STANDARD_KEYS.has(k)) continue;
          if (typeof v === 'function') continue;
          widgetConfig[k] = v;
        }
        return { ...w, id: widgetId, config: { ...(w.config || {}), ...widgetConfig } };
      });

      // BLOCKING: Create submission
      let finalRequestId;
      try {
        finalRequestId = await SubService.createSubmission(requestId, widgetsWithIds, req.user, req.env, headerWidgets);
      } catch (submissionErr) {
        // Rollback: soft-delete all created widgets
        for (const cw of createdWidgets) {
          try { await WidgetData.deleteWidget(cw.widget.widgetId, req.env); } catch { /* best-effort */ }
        }
        throw submissionErr;
      }

      // ── Step 3: Auto-approve for SUPER_ADMIN ──
      if (req.user.role === 'SUPER_ADMIN') {
        try {
          await SubService.updateRequestStatus(finalRequestId, 'APPROVED', req.user, req.env);
          const widgetIds = createdWidgets.map(cw => cw.widget.widgetId);
          if (widgetIds.length > 0) {
            await WidgetData.updateWidgetStatuses(widgetIds, 'APPROVED');
          }
        } catch (approveErr) {
          console.warn('[requests POST /] Auto-approve failed (submission still PENDING):', approveErr.message);
        }
      }

      const created = await SubService.fetchRequestById(finalRequestId, req.env);
      return res.status(201).json(created);
    }

    // ── Path B: Existing widget IDs ──
    if (!widgetIds || !Array.isArray(widgetIds) || widgetIds.length === 0) {
      return res.status(400).json({ error: 'widgetIds array or widgets array is required' });
    }

    const widgets = await WidgetData.findWidgetsByIds(widgetIds);

    const widgetSnapshots = widgets.map((w, i) => ({
      id: w.widgetId, type: w.type, slug: w.slug,
      title: w.title, titleHi: w.titleHi,
      pnc: w.pnc, config: w.config, products: w.products,
      sortOrder: i,
    }));

    const newRequestId = await SubService.createSubmission(null, widgetSnapshots, req.user, req.env, headerWidgets);

    const created = await SubService.fetchRequestById(newRequestId, req.env);
    res.status(201).json(created);
  } catch (err) {
    console.error('[requests POST /] Error:', err.message || err, err.stack);
    return res.status(500).json({ error: 'Submit failed', details: err.message || String(err), stack: (err.stack || '').split('\n').slice(0, 3) });
  }
});

// ── POST /requests/:id/approve ──
router.post('/:id/approve', async (req, res, next) => {
  try {
    if (req.user.role !== 'CHECKER' && req.user.role !== 'SUPER_ADMIN') {
      return res.status(403).json({ error: 'Only CHECKER or SUPER_ADMIN can approve' });
    }

    const request = await SubService.fetchRequestById(req.params.id, req.env);
    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.status === 'APPROVED') {
      return res.json({ id: req.params.id, status: 'APPROVED', updatedAt: request.updatedAt, alreadyApproved: true });
    }
    if (request.status !== 'PENDING') {
      return res.status(400).json({ error: `Cannot approve request in ${request.status} status` });
    }

    const { selectedWidgetIds } = req.body;
    const widgetIds = selectedWidgetIds
      ? request.requestWidgets.filter(rw => selectedWidgetIds.includes(rw.widgetId)).map(rw => rw.widgetId)
      : request.requestWidgets.map(rw => rw.widgetId);

    if (widgetIds.length === 0) {
      return res.status(400).json({ error: 'No valid widget IDs to approve' });
    }

    // Atomic: only update if still PENDING (DB-level CAS prevents double-approve)
    await SubService.updateRequestStatus(req.params.id, 'APPROVED', req.user, req.env, {
      expectedStatus: 'PENDING',
    });

    // Update widget statuses — if this fails, retry once before rolling back
    try {
      await WidgetData.updateWidgetStatuses(widgetIds, 'APPROVED');
    } catch (widgetErr) {
      console.error('[approve] Widget status update failed, retrying:', widgetErr.message);
      try {
        await WidgetData.updateWidgetStatuses(widgetIds, 'APPROVED');
      } catch (retryErr) {
        console.error('[approve] Retry failed, rolling back submission status:', retryErr.message);
        await SubService.updateRequestStatus(req.params.id, 'PENDING', req.user, req.env).catch(() => {});
        throw retryErr;
      }
    }

    res.json({ id: req.params.id, status: 'APPROVED', updatedAt: new Date().toISOString() });
  } catch (err) {
    if (err.status === 409) {
      return res.status(409).json({ error: err.message });
    }
    console.error('[requests POST /:id/approve] Error:', err.message);
    if (err.message && err.message.includes('streaming buffer')) {
      return res.status(409).json({ error: 'Widget was just submitted. Please wait 1-2 minutes before approving (BigQuery streaming buffer delay).' });
    }
    return res.status(500).json({ error: 'Approve failed', details: err.message || String(err) });
  }
});

// ── POST /requests/:id/reject ──
router.post('/:id/reject', async (req, res, next) => {
  try {
    if (req.user.role !== 'CHECKER' && req.user.role !== 'SUPER_ADMIN') {
      return res.status(403).json({ error: 'Only CHECKER or SUPER_ADMIN can reject' });
    }

    const request = await SubService.fetchRequestById(req.params.id, req.env);
    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.status !== 'PENDING') {
      return res.status(400).json({ error: `Cannot reject request in ${request.status} status` });
    }

    const { reason } = req.body;

    // Atomic: only update if still PENDING
    await SubService.updateRequestStatus(req.params.id, 'REJECTED', req.user, req.env, {
      expectedStatus: 'PENDING',
      rejectionReason: reason || '',
    });

    const widgetIds = request.requestWidgets.map(rw => rw.widgetId);
    try {
      await WidgetData.updateWidgetStatuses(widgetIds, 'REJECTED');
    } catch (widgetErr) {
      console.error('[reject] Widget status update failed, retrying:', widgetErr.message);
      try {
        await WidgetData.updateWidgetStatuses(widgetIds, 'REJECTED');
      } catch (retryErr) {
        console.error('[reject] Retry failed, rolling back submission status:', retryErr.message);
        await SubService.updateRequestStatus(req.params.id, 'PENDING', req.user, req.env).catch(() => {});
        throw retryErr;
      }
    }

    res.json({ id: req.params.id, status: 'REJECTED', updatedAt: new Date().toISOString() });
  } catch (err) {
    if (err.status === 409) {
      return res.status(409).json({ error: err.message });
    }
    console.error('[requests POST /:id/reject] Error:', err.message);
    if (err.message && err.message.includes('streaming buffer')) {
      return res.status(409).json({ error: 'Please wait 1-2 minutes before rejecting (BigQuery streaming buffer delay).' });
    }
    return res.status(500).json({ error: 'Reject failed', details: err.message || String(err) });
  }
});

// ── POST /requests/:id/reopen ──
router.post('/:id/reopen', async (req, res, next) => {
  try {
    if (req.user.role !== 'CHECKER' && req.user.role !== 'SUPER_ADMIN') {
      return res.status(403).json({ error: 'Only CHECKER or SUPER_ADMIN can reopen' });
    }

    const request = await SubService.fetchRequestById(req.params.id, req.env);
    if (!request) return res.status(404).json({ error: 'Request not found' });
    if (request.status !== 'APPROVED' && request.status !== 'REJECTED') {
      return res.status(400).json({ error: `Cannot reopen request in ${request.status} status` });
    }

    const prevStatus = request.status;
    await SubService.updateRequestStatus(req.params.id, 'PENDING', req.user, req.env, {
      rejectionReason: '',
    });

    const widgetIds = request.requestWidgets.map(rw => rw.widgetId);
    try {
      await WidgetData.updateWidgetStatuses(widgetIds, 'PENDING');
    } catch (widgetErr) {
      console.error('[reopen] Widget status update failed, rolling back:', widgetErr.message);
      await SubService.updateRequestStatus(req.params.id, prevStatus, req.user, req.env).catch(() => {});
      throw widgetErr;
    }

    res.json({ id: req.params.id, status: 'PENDING', updatedAt: new Date().toISOString() });
  } catch (err) {
    console.error('[requests POST /:id/reopen] Error:', err.message);
    if (err.message && err.message.includes('streaming buffer')) {
      return res.status(409).json({ error: 'Please wait 1-2 minutes before reopening (BigQuery streaming buffer delay).' });
    }
    return res.status(500).json({ error: 'Reopen failed', details: err.message || String(err) });
  }
});

export default router;
